# Generated by Django 3.0.3 on 2020-02-05 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grupos', '__first__'),
        ('congreso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diputado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('apellidos', models.CharField(max_length=120)),
                ('nacimiento', models.DateField(blank=True, null=True)),
                ('grupo_parlamentario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diputados', to='grupos.GrupoParlamentario')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diputados', to='congreso.Provincia')),
            ],
        ),
    ]
