# Generated by Django 3.0.3 on 2022-02-25 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '__first__'),
        ('congreso', '0002_circunscripcionelectoral_congreso_hemiciclo_legislatura'),
        ('diputados', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diputado',
            name='grupo_parlamentario',
        ),
        migrations.AddField(
            model_name='diputado',
            name='grupos_parlamentarios',
            field=models.ManyToManyField(related_name='diputados', to='grupos.GrupoParlamentario'),
        ),
        migrations.AlterField(
            model_name='diputado',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diputados', to='congreso.CircunscripcionElectoral'),
        ),
        migrations.CreateModel(
            name='ActaDiputado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diputado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actas', to='diputados.Diputado')),
                ('hemiciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diputados', to='congreso.Hemiciclo')),
            ],
        ),
        migrations.AddField(
            model_name='diputado',
            name='hemiciclos',
            field=models.ManyToManyField(through='diputados.ActaDiputado', to='congreso.Hemiciclo'),
        ),
    ]
