# Generated by Django 3.0.3 on 2022-02-25 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('congreso', '0003_auto_20220225_0003'),
        ('diputados', '0002_auto_20220225_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actadiputado',
            name='diputado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diputados.Diputado'),
        ),
        migrations.AlterField(
            model_name='actadiputado',
            name='hemiciclo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='congreso.Hemiciclo'),
        ),
        migrations.AlterField(
            model_name='diputado',
            name='hemiciclos',
            field=models.ManyToManyField(related_name='diputados', through='diputados.ActaDiputado', to='congreso.Hemiciclo'),
        ),
    ]
