# Generated by Django 3.0.3 on 2022-02-25 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('congreso', '0006_auto_20220225_0152'),
        ('diputados', '0003_auto_20220225_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='actadiputado',
            name='asiento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='congreso.AsientosCongreso'),
        ),
    ]
