# Generated by Django 3.0.3 on 2022-02-25 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0003_grupoparlamentario_color'),
        ('diputados', '0004_actadiputado_asiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='actadiputado',
            name='grupo_parlamentario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grupos.GrupoParlamentario'),
        ),
    ]
