# Generated by Django 3.0.3 on 2020-02-05 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('habitantes', models.IntegerField()),
                ('escanos', models.IntegerField()),
            ],
        ),
    ]
