# Generated by Django 3.0.3 on 2022-02-25 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congreso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CircunscripcionElectoral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32, verbose_name='Nombre de la circunscripción')),
                ('habitantes', models.IntegerField(verbose_name='Número de habitantes')),
                ('escanos', models.IntegerField(verbose_name='Número de escaños')),
            ],
            options={
                'verbose_name': 'Circunscripción Electoral',
                'verbose_name_plural': 'Circunscripciones Electorales',
            },
        ),
        migrations.CreateModel(
            name='Congreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Hemiciclo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fin', models.DateField(verbose_name='Fecha de fin')),
            ],
        ),
        migrations.CreateModel(
            name='Legislatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32, verbose_name='Nombre de la Legislatura')),
                ('inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fin', models.DateField(verbose_name='Fecha de cierre')),
            ],
            options={
                'verbose_name': 'Legislatura',
                'verbose_name_plural': 'Legislaturas',
            },
        ),
    ]
