# Generated by Django 3.0.3 on 2022-02-25 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diputados', '0002_auto_20220225_0003'),
        ('congreso', '0002_circunscripcionelectoral_congreso_hemiciclo_legislatura'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Provincia',
        ),
        migrations.AddField(
            model_name='congreso',
            name='legislatura',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='congreso', to='congreso.Legislatura'),
        ),
    ]
