# Generated by Django 3.0.3 on 2022-02-25 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congreso', '0003_auto_20220225_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legislatura',
            name='fin',
            field=models.DateField(null=True, verbose_name='Fecha de cierre'),
        ),
    ]
