# Generated by Django 3.0.3 on 2022-02-25 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diputados', '0005_actadiputado_grupo_parlamentario'),
        ('congreso', '0006_auto_20220225_0152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sesion', models.IntegerField(verbose_name='Número de sesión')),
                ('fecha', models.DateField(verbose_name='Fecha de la sesión')),
                ('congreso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='congreso.Congreso')),
            ],
        ),
        migrations.CreateModel(
            name='Votacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_votacion', models.IntegerField(verbose_name='Posición')),
                ('resultado', models.CharField(choices=[('Si', 'Sí'), ('No', 'No')], max_length=8, verbose_name='Resultado de la votación')),
                ('presentes', models.IntegerField(verbose_name='Recuento de presentes')),
                ('favor', models.IntegerField(verbose_name='Recuento de votos a favor')),
                ('contra', models.IntegerField(verbose_name='Recuento de votos en contra')),
                ('abstenciones', models.IntegerField(verbose_name='Recuento de abstenciones')),
                ('no_votan', models.IntegerField(verbose_name='Recuento de no-votos')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votaciones', to='votaciones.Sesion')),
            ],
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diputado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votos', to='diputados.ActaDiputado')),
                ('votacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='votaciones.Votacion')),
            ],
        ),
    ]
