# Generated by Django 3.0.3 on 2022-02-25 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('congreso', '0005_auto_20220225_0029'),
        ('grupos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupoparlamentario',
            name='congresos',
            field=models.ManyToManyField(related_name='grupos_parlamentarios', to='congreso.Congreso'),
        ),
    ]
